console.log(1 > 2); // false
console.log(1 < 2); // true
console.log(1 >= 2); // false
console.log(1 <= 2); // true
console.log(1 == 2); // false
console.log(1 != 2); // true
console.log(1 === 2); // false
console.log(1 !== 2); // true
console.log(1 === '1'); // false
console.log(1 == '1'); // true
console.log(1 != '1'); // false 
console.log(1 !== '1'); // true
console.log(1 == true); // true
console.log(1 === true); // false
console.log(1 == false); // false
console.log(1 === false); // false
console.log(0 == false); // true
console.log(0 === false); // false
console.log(0 == true); // false
console.log(0 === true); // false
console.log('' == false); // true
console.log('' === false); // false
console.log('' == true); // false
console.log('' === true); // false
console.log('0' == false); // true
console.log('0' === false); // false
console.log('0' == true); // false
console.log('0' === true); // false
console.log('1' == false); // false
console.log('1' === false); // false
console.log(null == false); // false
console.log(null === false); // false
console.log(undefined == false); // false
console.log(undefined === false); // false
console.log(null == undefined); // true
console.log(null === undefined); // false
console.log(null == 0); // false
console.log(null === 0); // false
console.log(undefined == 0); // false
console.log(undefined === 0); // false
console.log(null == ''); // false
console.log(null === ''); // false
console.log(undefined == ''); // false
console.log(undefined === ''); // false
console.log(null == '0'); // false
console.log(null === '0'); // false
console.log(null > 0); // false
console.log(null < 0); // false
console.log(null >= 0); // true
console.log(null <= 0); // true
console.log(undefined > 0); // false
console.log(undefined < 0); // false
console.log(undefined >= 0); // false
console.log(undefined <= 0); // false
console.log(null > undefined); // false
console.log(null < undefined); // false
console.log(null >= undefined); // true
console.log(null <= undefined); // true
console.log(null > ''); // false
console.log(null < ''); // false
console.log(null >= ''); // true
console.log(null <= ''); // true    
console.log(undefined > ''); // false
console.log(undefined < ''); // false
console.log(undefined >= ''); // false
console.log(undefined <= ''); // false
console.log(null > '0'); // false
console.log(null < '0'); // false
console.log(null >= '0'); // true
console.log(null <= '0'); // true
console.log(null > '1'); // false
console.log(null < '1'); // false
console.log(null >= '1'); // false
console.log(null <= '1'); // false
console.log(undefined > '0'); // false
console.log(undefined < '0'); // false
console.log(undefined >= '0'); // false
console.log(undefined <= '0'); // false
console.log(undefined > '1'); // false
console.log(undefined < '1'); // false      
console.log(undefined >= '1'); // false
console.log(undefined <= '1'); // false
console.log('' > '0'); // false
console.log('' < '0'); // true
console.log('' >= '0'); // true
console.log('' <= '0'); // false
console.log('' > '1'); // false
console.log('' < '1'); // true
console.log('' >= '1'); // false